-- Socializando — Módulo de Oficinas v4.6.0
-- PostgreSQL / Supabase
-- Regra central: somente inscrições CONFIRMED consomem vaga.

create extension if not exists pgcrypto;

create table if not exists public.workshops (
  id uuid primary key default gen_random_uuid(),
  experience_key text not null,
  slug text not null unique,
  title text not null,
  short_description text,
  event_date date not null,
  start_time time,
  end_time time,
  minimum_age integer not null default 5 check (minimum_age >= 0),
  age_label text,
  price_cents integer not null check (price_cents >= 0),
  capacity integer not null check (capacity > 0),
  status text not null default 'draft'
    check (status in ('draft','open','closed','sold_out','archived')),
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migração segura caso a tabela já exista de uma etapa anterior do MVP.
alter table public.workshops add column if not exists experience_key text;
alter table public.workshops add column if not exists minimum_age integer default 5;
update public.workshops set experience_key = slug where experience_key is null;
update public.workshops set minimum_age = 5 where minimum_age is null;
alter table public.workshops alter column experience_key set not null;
alter table public.workshops alter column minimum_age set not null;

create index if not exists workshops_experience_date_idx
  on public.workshops (experience_key, event_date, start_time);

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid(),
  workshop_id uuid not null references public.workshops(id) on delete restrict,

  responsible_name text not null,
  responsible_whatsapp text not null,
  responsible_email text,

  child_name text not null,
  child_birth_date date,
  child_age integer check (child_age is null or child_age between 0 and 18),
  notes text,

  amount_cents integer not null check (amount_cents >= 0),
  payment_reference text not null unique,

  status text not null default 'pending_payment'
    check (status in ('pending_payment','payment_reported','confirmed','cancelled')),

  payment_reported_at timestamptz,
  confirmed_at timestamptz,
  confirmed_by uuid,
  cancelled_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.registrations add column if not exists public_token uuid default gen_random_uuid();
update public.registrations set public_token = gen_random_uuid() where public_token is null;
alter table public.registrations alter column public_token set not null;

create unique index if not exists registrations_public_token_idx
  on public.registrations (public_token);
create index if not exists registrations_workshop_status_idx
  on public.registrations (workshop_id, status);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_emails (
  email text primary key check (email = lower(trim(email))),
  active boolean not null default true,
  created_at timestamptz not null default now()
);


create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_email text,
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc);


-- Artes públicas das oficinas. O bucket permanece dentro da cota gratuita do projeto
-- e aceita somente arquivos de imagem de até 5 MB. Uploads/alterações são restritos
-- a usuários administrativos do módulo; leitura pública ocorre pelo endpoint público
-- do próprio Storage.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'workshop-artworks',
  'workshop-artworks',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.is_workshop_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $admin$
  select
    exists (
      select 1
      from public.admin_users a
      where a.user_id = auth.uid()
    )
    or exists (
      select 1
      from public.admin_emails e
      where e.active = true
        and e.email = lower(auth.jwt()->>'email')
    );
$admin$;

create or replace function public.audit_workshop_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $audit_workshop$
declare
  v_action text;
  v_id uuid;
begin
  if auth.uid() is null or not public.is_workshop_admin() then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  v_action := case tg_op
    when 'INSERT' then 'workshop_created'
    when 'UPDATE' then 'workshop_updated'
    when 'DELETE' then 'workshop_deleted'
    else lower(tg_op)
  end;

  v_id := case when tg_op = 'DELETE' then old.id else new.id end;

  insert into public.admin_audit_log (
    actor_user_id, actor_email, entity_type, entity_id, action, details
  ) values (
    auth.uid(),
    lower(coalesce(auth.jwt()->>'email','')),
    'workshop',
    v_id,
    v_action,
    case
      when tg_op = 'INSERT' then jsonb_build_object(
        'title', new.title, 'date', new.event_date, 'time', new.start_time,
        'capacity', new.capacity, 'price_cents', new.price_cents, 'status', new.status
      )
      when tg_op = 'UPDATE' then jsonb_build_object(
        'before', jsonb_build_object(
          'title', old.title, 'date', old.event_date, 'start_time', old.start_time,
          'end_time', old.end_time, 'capacity', old.capacity,
          'price_cents', old.price_cents, 'status', old.status
        ),
        'after', jsonb_build_object(
          'title', new.title, 'date', new.event_date, 'start_time', new.start_time,
          'end_time', new.end_time, 'capacity', new.capacity,
          'price_cents', new.price_cents, 'status', new.status
        )
      )
      else jsonb_build_object('title', old.title, 'status', old.status)
    end
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$audit_workshop$;

create or replace function public.audit_registration_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $audit_registration$
begin
  if auth.uid() is null or not public.is_workshop_admin() then
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.admin_audit_log (
      actor_user_id, actor_email, entity_type, entity_id, action, details
    ) values (
      auth.uid(),
      lower(coalesce(auth.jwt()->>'email','')),
      'registration',
      new.id,
      'registration_status_changed',
      jsonb_build_object(
        'workshop_id', new.workshop_id,
        'payment_reference', new.payment_reference,
        'from', old.status,
        'to', new.status
      )
    );
  end if;

  return new;
end;
$audit_registration$;

drop trigger if exists workshops_admin_audit on public.workshops;
create trigger workshops_admin_audit
after insert or update or delete on public.workshops
for each row execute function public.audit_workshop_admin_change();

drop trigger if exists registrations_admin_audit on public.registrations;
create trigger registrations_admin_audit
after update of status on public.registrations
for each row execute function public.audit_registration_admin_change();


create or replace view public.workshop_availability
with (security_invoker = true)
as
select
  w.id,
  w.experience_key,
  w.slug,
  w.title,
  w.short_description,
  w.event_date,
  w.start_time,
  w.end_time,
  w.minimum_age,
  w.age_label,
  w.price_cents,
  w.capacity,
  w.status,
  w.image_url,
  count(r.id) filter (where r.status = 'confirmed')::integer as confirmed_count,
  greatest(
    w.capacity - count(r.id) filter (where r.status in ('payment_reported','confirmed'))::integer,
    0
  ) as available_spots
from public.workshops w
left join public.registrations r on r.workshop_id = w.id
group by w.id;

create or replace function public.list_public_workshops()
returns table (
  id uuid,
  experience_key text,
  slug text,
  title text,
  short_description text,
  event_date date,
  start_time time,
  end_time time,
  minimum_age integer,
  age_label text,
  price_cents integer,
  capacity integer,
  status text,
  image_url text,
  confirmed_count integer,
  available_spots integer
)
language sql
stable
security definer
set search_path = public
as $sql$
  select
    w.id, w.experience_key, w.slug, w.title, w.short_description,
    w.event_date, w.start_time, w.end_time, w.minimum_age, w.age_label,
    w.price_cents, w.capacity, w.status, w.image_url,
    count(r.id) filter (where r.status = 'confirmed')::integer as confirmed_count,
    greatest(w.capacity - count(r.id) filter (where r.status in ('payment_reported','confirmed'))::integer, 0) as available_spots
  from public.workshops w
  left join public.registrations r on r.workshop_id = w.id
  where w.status in ('open','sold_out')
  group by w.id
  order by w.event_date, w.start_time;
$sql$;

create or replace function public.prevent_overbooking()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_capacity integer;
  v_occupied integer;
begin
  if new.status in ('payment_reported','confirmed')
     and old.status not in ('payment_reported','confirmed') then
    select capacity into v_capacity
    from public.workshops
    where id = new.workshop_id
    for update;

    select count(*)::integer into v_occupied
    from public.registrations
    where workshop_id = new.workshop_id
      and status in ('payment_reported','confirmed')
      and id <> new.id;

    if v_occupied >= v_capacity then
      raise exception 'Oficina sem vagas disponíveis';
    end if;
  end if;

  if new.status = 'confirmed' and old.status is distinct from 'confirmed' then
    new.confirmed_at := coalesce(new.confirmed_at, now());
    new.confirmed_by := coalesce(new.confirmed_by, auth.uid());
  end if;

  if new.status = 'payment_reported' and old.status is distinct from 'payment_reported' then
    new.payment_reported_at := coalesce(new.payment_reported_at, now());
  end if;

  if new.status = 'cancelled' and old.status is distinct from 'cancelled' then
    new.cancelled_at := coalesce(new.cancelled_at, now());
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists registrations_prevent_overbooking on public.registrations;
create trigger registrations_prevent_overbooking
before update of status on public.registrations
for each row execute function public.prevent_overbooking();

create or replace function public.touch_workshop_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists workshops_touch_updated_at on public.workshops;
create trigger workshops_touch_updated_at
before update on public.workshops
for each row execute function public.touch_workshop_updated_at();

create or replace function public.create_public_registration(
  p_workshop_id uuid,
  p_responsible_name text,
  p_responsible_whatsapp text,
  p_responsible_email text,
  p_child_name text,
  p_child_age integer,
  p_child_birth_date date default null,
  p_notes text default null
)
returns table (
  registration_id uuid,
  public_token uuid,
  amount_cents integer,
  payment_reference text,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workshop public.workshops%rowtype;
  v_id uuid := gen_random_uuid();
  v_token uuid := gen_random_uuid();
  v_reference text;
begin
  select w.* into v_workshop
  from public.workshops w
  where w.id = p_workshop_id and w.status = 'open';

  if not found then
    raise exception 'Oficina indisponível para inscrição';
  end if;

  if p_responsible_name is null or length(trim(p_responsible_name)) < 3 then
    raise exception 'Nome do responsável inválido';
  end if;
  if p_responsible_whatsapp is null or length(regexp_replace(p_responsible_whatsapp, '\D', '', 'g')) < 10 then
    raise exception 'WhatsApp inválido';
  end if;
  if p_child_name is null or length(trim(p_child_name)) < 2 then
    raise exception 'Nome da criança inválido';
  end if;
  if p_child_age is null or p_child_age < v_workshop.minimum_age then
    raise exception 'Idade abaixo da faixa mínima da oficina';
  end if;

  if (
    select count(*) from public.registrations r
    where r.workshop_id = p_workshop_id
      and r.status in ('payment_reported','confirmed')
  ) >= v_workshop.capacity then
    raise exception 'Oficina sem vagas disponíveis';
  end if;

  v_reference := 'SJ' || upper(substr(replace(v_id::text, '-', ''), 1, 20));

  insert into public.registrations (
    id, public_token, workshop_id,
    responsible_name, responsible_whatsapp, responsible_email,
    child_name, child_age, child_birth_date, notes,
    amount_cents, payment_reference, status
  ) values (
    v_id, v_token, p_workshop_id,
    trim(p_responsible_name), trim(p_responsible_whatsapp), nullif(trim(p_responsible_email), ''),
    trim(p_child_name), p_child_age, p_child_birth_date, nullif(trim(p_notes), ''),
    v_workshop.price_cents, v_reference, 'pending_payment'
  );

  return query
  select v_id, v_token, v_workshop.price_cents, v_reference, 'pending_payment'::text;
end;
$$;

create or replace function public.report_public_payment(
  p_registration_id uuid,
  p_public_token uuid
)
returns table (status text, payment_reported_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.registrations as r
  set status = 'payment_reported',
      payment_reported_at = coalesce(r.payment_reported_at, now()),
      updated_at = now()
  where r.id = p_registration_id
    and r.public_token = p_public_token
    and r.status = 'pending_payment';

  if not exists (
    select 1 from public.registrations
    where id = p_registration_id and public_token = p_public_token
  ) then
    raise exception 'Inscrição não encontrada';
  end if;

  return query
  select r.status, r.payment_reported_at
  from public.registrations r
  where r.id = p_registration_id and r.public_token = p_public_token;
end;
$$;

alter table public.workshops enable row level security;
alter table public.registrations enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_emails enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists "public can read open workshops" on public.workshops;
create policy "public can read open workshops"
on public.workshops
for select
to anon
using (status in ('open','sold_out'));

drop policy if exists "admins can read all workshops" on public.workshops;
drop policy if exists "admins can manage workshops" on public.workshops;
drop policy if exists "admins can select workshops" on public.workshops;
drop policy if exists "admins can insert workshops" on public.workshops;
drop policy if exists "admins can update workshops" on public.workshops;
drop policy if exists "admins can delete workshops" on public.workshops;

create policy "admins can select workshops"
on public.workshops
for select
to authenticated
using (public.is_workshop_admin());

create policy "admins can insert workshops"
on public.workshops
for insert
to authenticated
with check (public.is_workshop_admin());

create policy "admins can update workshops"
on public.workshops
for update
to authenticated
using (public.is_workshop_admin())
with check (public.is_workshop_admin());

create policy "admins can delete workshops"
on public.workshops
for delete
to authenticated
using (public.is_workshop_admin());


-- Storage: leitura pública decorre do bucket público; escrita exige admin autenticado.
drop policy if exists "workshop admins can read artworks" on storage.objects;
drop policy if exists "workshop admins can upload artworks" on storage.objects;
drop policy if exists "workshop admins can update artworks" on storage.objects;
drop policy if exists "workshop admins can delete artworks" on storage.objects;

create policy "workshop admins can read artworks"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'workshop-artworks'
  and public.is_workshop_admin()
);

create policy "workshop admins can upload artworks"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'workshop-artworks'
  and public.is_workshop_admin()
);

create policy "workshop admins can update artworks"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'workshop-artworks'
  and public.is_workshop_admin()
)
with check (
  bucket_id = 'workshop-artworks'
  and public.is_workshop_admin()
);

create policy "workshop admins can delete artworks"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'workshop-artworks'
  and public.is_workshop_admin()
);


drop policy if exists "admins can read audit log" on public.admin_audit_log;
create policy "admins can read audit log"
on public.admin_audit_log
for select
to authenticated
using (public.is_workshop_admin());

drop policy if exists "admins can read registrations" on public.registrations;
create policy "admins can read registrations"
on public.registrations
for select
to authenticated
using (public.is_workshop_admin());

drop policy if exists "admins can update registrations" on public.registrations;
create policy "admins can update registrations"
on public.registrations
for update
to authenticated
using (public.is_workshop_admin())
with check (public.is_workshop_admin());

revoke all on public.registrations from anon;
revoke all on public.admin_audit_log from anon;
revoke all on public.admin_users from anon, authenticated;
revoke all on public.admin_emails from anon, authenticated;
revoke all on function public.is_workshop_admin() from public;
revoke execute on function public.is_workshop_admin() from anon;

grant select on public.workshops to anon;
grant select, insert, update on public.workshops to authenticated;
grant select, update on public.registrations to authenticated;
grant select on public.admin_audit_log to authenticated;
revoke all on public.workshop_availability from anon;
grant select on public.workshop_availability to authenticated;
revoke all on function public.audit_workshop_admin_change() from public, anon, authenticated;
revoke all on function public.audit_registration_admin_change() from public, anon, authenticated;

revoke all on function public.list_public_workshops() from public;
revoke all on function public.list_public_workshops() from authenticated;
revoke all on function public.create_public_registration(uuid,text,text,text,text,integer,date,text) from public;
revoke all on function public.create_public_registration(uuid,text,text,text,text,integer,date,text) from authenticated;
revoke all on function public.report_public_payment(uuid,uuid) from public;
revoke all on function public.report_public_payment(uuid,uuid) from authenticated;

grant execute on function public.list_public_workshops() to anon;
grant execute on function public.create_public_registration(uuid,text,text,text,text,integer,date,text) to anon;
grant execute on function public.report_public_payment(uuid,uuid) to anon;
grant execute on function public.is_workshop_admin() to authenticated;


-- =========================================================
-- Socializando — Fundação financeira V5.0 (Sicredi Pix)
-- Compatibilidade: permanece INATIVA por padrão.
-- Oficinas existentes seguem em payment_mode = 'manual_pix'.
-- =========================================================

alter table public.workshops
  add column if not exists payment_mode text not null default 'manual_pix',
  add column if not exists reservation_minutes integer not null default 15;

alter table public.workshops drop constraint if exists workshops_payment_mode_check;
alter table public.workshops add constraint workshops_payment_mode_check
  check (payment_mode in ('manual_pix','sicredi_api'));

alter table public.workshops drop constraint if exists workshops_reservation_minutes_check;
alter table public.workshops add constraint workshops_reservation_minutes_check
  check (reservation_minutes between 5 and 60);

alter table public.registrations
  add column if not exists reservation_expires_at timestamptz,
  add column if not exists payment_confirmed_at timestamptz;

alter table public.registrations drop constraint if exists registrations_status_check;
alter table public.registrations add constraint registrations_status_check
  check (status in ('pending_payment','payment_reported','confirmed','cancelled','expired'));

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references public.registrations(id) on delete restrict,
  provider text not null default 'sicredi',
  provider_txid text not null,
  amount_cents integer not null check (amount_cents >= 0),
  status text not null default 'created'
    check (status in ('created','paid','expired','cancelled','failed','refunded','review')),
  pix_copy_paste text,
  provider_location text,
  end_to_end_id text,
  expires_at timestamptz,
  paid_at timestamptz,
  last_checked_at timestamptz,
  provider_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_txid)
);

create index if not exists payment_transactions_registration_idx
  on public.payment_transactions (registration_id, created_at desc);
create index if not exists payment_transactions_status_expiry_idx
  on public.payment_transactions (status, expires_at);
create unique index if not exists payment_transactions_e2eid_idx
  on public.payment_transactions (end_to_end_id)
  where end_to_end_id is not null;
create index if not exists registrations_reservation_expiry_idx
  on public.registrations (workshop_id, reservation_expires_at)
  where status = 'pending_payment';

alter table public.payment_transactions enable row level security;
revoke all on public.payment_transactions from public, anon;

drop policy if exists "admins can read payment transactions" on public.payment_transactions;
create policy "admins can read payment transactions"
on public.payment_transactions
for select
to authenticated
using (public.is_workshop_admin());

grant select on public.payment_transactions to authenticated;

create or replace function public.touch_payment_transaction_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists payment_transactions_touch_updated_at on public.payment_transactions;
create trigger payment_transactions_touch_updated_at
before update on public.payment_transactions
for each row execute function public.touch_payment_transaction_updated_at();

create or replace function public.reserve_pix_registration(
  p_workshop_id uuid,
  p_responsible_name text,
  p_responsible_whatsapp text,
  p_responsible_email text,
  p_child_name text,
  p_child_age integer,
  p_child_birth_date date default null,
  p_notes text default null
)
returns table (
  registration_id uuid,
  public_token uuid,
  amount_cents integer,
  payment_reference text,
  reservation_expires_at timestamptz,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_workshop public.workshops%rowtype;
  v_id uuid := gen_random_uuid();
  v_token uuid := gen_random_uuid();
  v_reference text;
  v_occupied integer;
  v_expires timestamptz;
begin
  select w.* into v_workshop
  from public.workshops w
  where w.id = p_workshop_id
    and w.status = 'open'
    and w.payment_mode = 'sicredi_api'
  for update;

  if not found then
    raise exception 'Oficina indisponível para checkout Pix automático';
  end if;

  if p_responsible_name is null or length(trim(p_responsible_name)) < 3 then
    raise exception 'Nome do responsável inválido';
  end if;
  if p_responsible_whatsapp is null or length(regexp_replace(p_responsible_whatsapp, '\\D', '', 'g')) < 10 then
    raise exception 'WhatsApp inválido';
  end if;
  if p_child_name is null or length(trim(p_child_name)) < 2 then
    raise exception 'Nome da criança inválido';
  end if;
  if p_child_age is null or p_child_age < v_workshop.minimum_age then
    raise exception 'Idade abaixo da faixa mínima da oficina';
  end if;

  update public.registrations
  set status = 'expired', updated_at = now()
  where workshop_id = p_workshop_id
    and status = 'pending_payment'
    and reservation_expires_at is not null
    and reservation_expires_at <= now();

  select count(*)::integer into v_occupied
  from public.registrations r
  where r.workshop_id = p_workshop_id
    and (
      r.status in ('payment_reported','confirmed')
      or (
        r.status = 'pending_payment'
        and r.reservation_expires_at is not null
        and r.reservation_expires_at > now()
      )
    );

  if v_occupied >= v_workshop.capacity then
    raise exception 'Oficina sem vagas disponíveis';
  end if;

  v_reference := 'SJ' || upper(substr(replace(v_id::text, '-', ''), 1, 20));
  v_expires := now() + make_interval(mins => v_workshop.reservation_minutes);

  insert into public.registrations (
    id, public_token, workshop_id,
    responsible_name, responsible_whatsapp, responsible_email,
    child_name, child_age, child_birth_date, notes,
    amount_cents, payment_reference, status, reservation_expires_at
  ) values (
    v_id, v_token, p_workshop_id,
    trim(p_responsible_name), trim(p_responsible_whatsapp), nullif(trim(p_responsible_email), ''),
    trim(p_child_name), p_child_age, p_child_birth_date, nullif(trim(p_notes), ''),
    v_workshop.price_cents, v_reference, 'pending_payment', v_expires
  );

  return query
  select v_id, v_token, v_workshop.price_cents, v_reference, v_expires, 'pending_payment'::text;
end;
$$;

revoke all on function public.reserve_pix_registration(uuid,text,text,text,text,integer,date,text) from public, anon, authenticated;
grant execute on function public.reserve_pix_registration(uuid,text,text,text,text,integer,date,text) to service_role;

create or replace function public.record_pix_charge(
  p_registration_id uuid,
  p_txid text,
  p_amount_cents integer,
  p_pix_copy_paste text,
  p_location text,
  p_expires_at timestamptz,
  p_provider_payload jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_registration public.registrations%rowtype;
  v_id uuid;
begin
  if p_txid !~ '^[A-Za-z0-9]{26,35}$' then raise exception 'txid inválido'; end if;

  select * into v_registration
  from public.registrations
  where id = p_registration_id
  for update;

  if not found or v_registration.status <> 'pending_payment' then
    raise exception 'Inscrição não está aguardando pagamento';
  end if;
  if p_amount_cents <> v_registration.amount_cents then
    raise exception 'Valor da cobrança divergente';
  end if;

  insert into public.payment_transactions (
    registration_id, provider, provider_txid, amount_cents, status,
    pix_copy_paste, provider_location, expires_at, provider_payload
  ) values (
    p_registration_id, 'sicredi', p_txid, p_amount_cents, 'created',
    nullif(p_pix_copy_paste,''), nullif(p_location,''), p_expires_at,
    coalesce(p_provider_payload,'{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_pix_charge(uuid,text,integer,text,text,timestamptz,jsonb) from public, anon, authenticated;
grant execute on function public.record_pix_charge(uuid,text,integer,text,text,timestamptz,jsonb) to service_role;

create or replace function public.confirm_pix_payment(
  p_txid text,
  p_amount_cents integer,
  p_paid_at timestamptz,
  p_end_to_end_id text default null,
  p_provider_payload jsonb default '{}'::jsonb
)
returns table (
  registration_id uuid,
  registration_status text,
  payment_status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.payment_transactions%rowtype;
  v_registration public.registrations%rowtype;
  v_capacity integer;
  v_confirmed integer;
begin
  select * into v_payment
  from public.payment_transactions
  where provider = 'sicredi' and provider_txid = p_txid
  for update;

  if not found then raise exception 'Cobrança não encontrada'; end if;

  select * into v_registration
  from public.registrations
  where id = v_payment.registration_id
  for update;

  if v_payment.status = 'paid' and v_registration.status = 'confirmed' then
    return query select v_registration.id, v_registration.status, v_payment.status;
    return;
  end if;

  if p_amount_cents <> v_payment.amount_cents or p_amount_cents <> v_registration.amount_cents then
    update public.payment_transactions
    set status='review', paid_at=coalesce(p_paid_at,now()),
        end_to_end_id=coalesce(p_end_to_end_id,end_to_end_id),
        provider_payload=coalesce(p_provider_payload,'{}'::jsonb), last_checked_at=now()
    where id=v_payment.id;
    return query select v_registration.id, v_registration.status, 'review'::text;
    return;
  end if;

  if v_registration.reservation_expires_at is not null
     and coalesce(p_paid_at,now()) > v_registration.reservation_expires_at then
    update public.payment_transactions
    set status='review', paid_at=coalesce(p_paid_at,now()),
        end_to_end_id=coalesce(p_end_to_end_id,end_to_end_id),
        provider_payload=coalesce(p_provider_payload,'{}'::jsonb), last_checked_at=now()
    where id=v_payment.id;
    return query select v_registration.id, v_registration.status, 'review'::text;
    return;
  end if;

  select capacity into v_capacity
  from public.workshops
  where id=v_registration.workshop_id
  for update;

  select count(*)::integer into v_confirmed
  from public.registrations
  where workshop_id=v_registration.workshop_id
    and status in ('payment_reported','confirmed')
    and id <> v_registration.id;

  if v_confirmed >= v_capacity then
    update public.payment_transactions
    set status='review', paid_at=coalesce(p_paid_at,now()),
        end_to_end_id=coalesce(p_end_to_end_id,end_to_end_id),
        provider_payload=coalesce(p_provider_payload,'{}'::jsonb), last_checked_at=now()
    where id=v_payment.id;
    return query select v_registration.id, v_registration.status, 'review'::text;
    return;
  end if;

  update public.payment_transactions
  set status='paid', paid_at=coalesce(p_paid_at,now()),
      end_to_end_id=coalesce(p_end_to_end_id,end_to_end_id),
      provider_payload=coalesce(p_provider_payload,'{}'::jsonb), last_checked_at=now()
  where id=v_payment.id;

  update public.registrations
  set status='confirmed',
      payment_confirmed_at=coalesce(payment_confirmed_at,coalesce(p_paid_at,now())),
      confirmed_at=coalesce(confirmed_at,coalesce(p_paid_at,now())),
      updated_at=now()
  where id=v_registration.id;

  return query
  select r.id, r.status, 'paid'::text
  from public.registrations r
  where r.id=v_registration.id;
end;
$$;

revoke all on function public.confirm_pix_payment(text,integer,timestamptz,text,jsonb) from public, anon, authenticated;
grant execute on function public.confirm_pix_payment(text,integer,timestamptz,text,jsonb) to service_role;

create or replace function public.get_public_registration_status(
  p_registration_id uuid,
  p_public_token uuid
)
returns table (
  status text,
  reservation_expires_at timestamptz,
  confirmed_at timestamptz,
  payment_status text
)
language sql
stable
security definer
set search_path = public
as $$
  select r.status, r.reservation_expires_at, r.confirmed_at,
    (
      select p.status
      from public.payment_transactions p
      where p.registration_id=r.id
      order by p.created_at desc
      limit 1
    ) as payment_status
  from public.registrations r
  where r.id=p_registration_id and r.public_token=p_public_token;
$$;

revoke all on function public.get_public_registration_status(uuid,uuid) from public;
grant execute on function public.get_public_registration_status(uuid,uuid) to anon, authenticated;

-- list_public_workshops passa a contar reservas válidas apenas quando a oficina
-- estiver explicitamente no modo sicredi_api. O modo manual preserva a V4.8.2.
create or replace function public.list_public_workshops()
returns table (
  id uuid, experience_key text, slug text, title text, short_description text,
  event_date date, start_time time, end_time time, minimum_age integer,
  age_label text, price_cents integer, capacity integer, status text,
  image_url text, confirmed_count integer, available_spots integer
)
language sql
stable
security definer
set search_path = public
as $sql$
  select
    w.id, w.experience_key, w.slug, w.title, w.short_description,
    w.event_date, w.start_time, w.end_time, w.minimum_age, w.age_label,
    w.price_cents, w.capacity, w.status, w.image_url,
    count(r.id) filter (where r.status = 'confirmed')::integer as confirmed_count,
    greatest(
      w.capacity - count(r.id) filter (
        where
          (
            w.payment_mode = 'sicredi_api'
            and (
              r.status in ('payment_reported','confirmed')
              or (
                r.status = 'pending_payment'
                and r.reservation_expires_at is not null
                and r.reservation_expires_at > now()
              )
            )
          )
          or
          (
            w.payment_mode <> 'sicredi_api'
            and r.status in ('payment_reported','confirmed')
          )
      )::integer,
      0
    ) as available_spots
  from public.workshops w
  left join public.registrations r on r.workshop_id = w.id
  where w.status in ('open','sold_out')
  group by w.id
  order by w.event_date, w.start_time;
$sql$;
